### ISSUE TITLE
[Petr] Design and implement the secure communication with a card

### ISSUE THREAD

**Issue by ValentinKuznetsov** [ValentinKuznetsov/jpass-smartcard#1]
Your first step should be to research  jpass.smartcard package and classes there.

See the APDU.class.

I would suggest the following:

**On the application side,**

It creates the instance of JavaCard class, which encapsulates the connection to the simulator (or physical card) and has the interface for sending APDU and returning the answer from the card.

The goal is to build an additional layer with API between the desktop app and the JavaCard class: probably, it should be called something like SecureCommunicationProvider.

After it gets initalized with a JavaCard instance, it should establish the secure channel between the card and the desktop app.

It will also have the API for sending requests(packets) to the JavaCard; this provider should take care of encrypting these packets and decrypting the responses.

**On the card side,**
There should be similar provider which decrypts the received packets and encrypts the packets which are to be sent.
It should be hooked somewhere in the 'process' method.

So, the task would be:
1)Think about architecture (^ you can take mine above or design yours)
2)Design the secure communication protocol (Find something known)
3)Implement all that.

**Comment by ValentinKuznetsov** [comment]
On the desktop side,  I would suggest the security communication to be in the CardsManager class.

CardsManager is a proxy between desktop and the applet - basically, the task is the following:
1)Establish the secure channel (change connectToCard method)
2)Change appropriate methods, such as: isPinUnlocked, setPin, verifyPin, encryptBytes, decryptBytes, where you would put the following:

encrypt(everything which goes to the card)
send data to card()
decrypt the response from the card()

**Comment by ValentinKuznetsov** [comment]
On the applet side, it would be something similar:

In the **process** method, the received data gets decrypted and used as it is used now
And just before returning the APDUs for the host, the data gets encrypted

**Comment by ValentinKuznetsov** [comment]
Please provide the design of the secure channel ASAP, so we can start implementing that. If you have difficulties, let me know, again, asap.

**Comment by JoystiC** [comment]
SecureChannel:
two keys:
DESKey keyMAC; 
DESKey keyENC;

each is 16 byte 3DES EDE key

two functions:
wrapResponseAPDU ( encrypt and build mac )
- incerement SSC ( send sequence counter ) 
- calculate and write mac

unwrapCommandAPDU ( verify mac and decrypt )
-  incerement SSC
- verify mac , then decrypt data 
- for mac verify using padding PAD_DATA = {(byte) 0x80, 0, 0, 0, 0, 0, 0, 0} + SSC

**Comment by JoystiC** [comment]
in applet there should be: 
SecureChannel secCh = new SecureChannel();
secCh.init()
init will clear keys and ssc , ( should be edited , keys are estabilished during connect stage and so on )
