### ISSUE TITLE
Secure channel

### ISSUE THREAD

**Issue by JoystiC** [ValentinKuznetsov/jpass-smartcard#3]
After 3 days of googling I cant really move on. What I found is GlobalPlatform API: http://www.win.tue.nl/pinpasjc/docs/apis/gp22/ which should probably help us to create secure channel. Ill probably know how to use it if we can get it working e.g create secure channel then:

SecureChannel sc = GPSystem.getSecureChannel();    -- this get error probably because card is not in SECURED mode but idk how to do it

EXT_AUTHENTICATE:
sc.processSecurity(apdu);

then we can use wrap unwarp functions for secure communication 
len = apdu.setIncomingAndReceive();
unwraped = sc.unwrap(buffer, (short) 0, inlength);
apdu.setOutgoingAndSend((short)0, inlength);

So what should we done to make secure channel working probably is:
send to APDUs to card:
INITIALIZE UPDATE
data: 8 bytes random data (host challenge)
then smart card generates its own random 8 byte , then it will take host challenge and smart card challenge derivation and encrypt it with static ENC key. ( how to create ENC key on card ? also will be same key like on desktop app?  ) result of this will be sesion key.

Then we should create something like cryptogram ( with using of session key ) which is computed by MAC operation then cryptogram is send back with card challenge to desktop app. 

EXTERNAL AUTHENTICATE
app got card cryptogram and card challenge so it compute its own cryptogram . Should be based on 3DES CBC mode.
In case of the equivalence of the received and computed card cryptograms, host cryptogram is send back to card together with MAC of whole APDU command (EXTERNAL AUTHENTICATE). Algorithm for host cryptogram is same with swapped host and card challenge.  Session encryption and MAC keys are then used to create confidential authenticated tunnel between smart card and PC application for all subsequent APDU commands. 

So i can generate random data on app and card also derive them and maybe ? Know hot to encrypt them with static ENC key then create cryptogram ( something like mac_3des_nulliv ( key, host_challenge + card_challenge ? ). 

then we create some kind of wrapper and communicate but this wrapper think already got http://www.win.tue.nl/pinpasjc/docs/apis/gp22/ and i hoped that before actions have that api too but i cant realy get it to work so maybe do it manualy hard way?

**Comment by JoystiC** [comment]
maybe it need some more time testing now I only read and get some information about this now when i wrote it it sound not that hard :D

**Comment by JoystiC** [comment]
So i can now do this:
SecureChannel secCh = GPSystem.getSecureChannel();
( using Global Platform , last time it crash at it ) 
now if i want to secCh.processSecurity(apdu); it crash no idea why maybe bad apdu?

**Comment by ValentinKuznetsov** [comment]
Closing this
